### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by soaka0721** [hallazie/yolov3_ocr_mxnet#1]
Hi. I'm interested in your project. 
Does this code work now? 
I do not know how to build it.

**Comment by hallazie** [comment]
> Hi. I'm interested in your project.
> Does this code work now?
> I do not know how to build it.

It works as I remembered but I didn't finish the pipeline, so you have to run train( ) function in yolo.py for training then manually run predict( ).  I would not recommend you to work on this project though.
